### ISSUE TITLE
Register to grader

### ISSUE THREAD

**Issue by kangwonlee** [eca21c/HelpDesk#10]
here is the info
org : eca20b
repo : eca20b-40-204-kangwonlee

**Comment by kangwon-naver** [comment]
org: your_org_here
repo: your_repo_name_here
Please use form above
Could not find the org name in comment

**Comment by kangwonlee** [comment]
org : eca20b
repo : eca20b-40-204-kangwonlee

will this work now

**Comment by kangwon-naver** [comment]
org: eca20b
repo: eca20b-40-204-kangwonlee
Processing request above

**Comment by kangwon-naver** [comment]
org: eca20b
repo: eca20b-40-204-kangwonlee
Success! Start your engine!
